### ISSUE TITLE
which LED strip is needed for the CV LED controller?

### ISSUE THREAD

**Issue by KeLaiFu** [JonathanBedrava/eurorack-cv-led-strip-controller#1]
just about to send the PCBs off to our friends in shenzhen and wanted to double check which format of RGB strip was requeired?

Also, whats the 3x one? I only see the gerbers and although it looks way to big for my needs, I am curious what it is...

**Comment by JonathanBedrava** [comment]
I've been using 5050 RGB strips. They have four pins for blue, green, red, and common ground.

The 3x version has three led strip controllers combined into one board. It's an even earlier version of this design and I wouldn't recommend using it.

**Comment by KeLaiFu** [comment]
thanks, I already have some 5050 ones in my shopping cart. I gave the PCB a bit of a redesign, and pending it actually still working I will make a PCB panel to suit. I'll share everything to my github (with credit of course) if it's ok with you.

**Comment by JonathanBedrava** [comment]
Absolutely! This was always intended for people who know better than me to improve upon. I look forward to seeing your enhancements!
